// Frases Motivacionais - Macro Counter
const FRASES = [
  // ── Motivação & Treino ─────────────────────────────────────────────
  ["A dor que você sente hoje será a força que você vai sentir amanhã.", "Arnold Schwarzenegger"],
  ["Não pare quando estiver cansado. Pare quando tiver terminado.", "David Goggins"],
  ["O corpo consegue quase tudo. É a mente que você tem que convencer.", "Anônimo"],
  ["A única má sessão de treino é aquela que não aconteceu.", "Anônimo"],
  ["Disciplina é a ponte entre metas e realizações.", "Jim Rohn"],
  ["Cada rep que você faz quando não quer é o que te separa de quem você quer ser.", "Anônimo"],
  ["O campeão não é feito no ginásio. É feito do que ele tem dentro — um desejo, um sonho, uma visão.", "Muhammad Ali"],
  ["A força não vem de vencer. A força vem da luta.", "Arnold Schwarzenegger"],
  ["A consistência bate o talento quando o talento não é consistente.", "Anônimo"],
  ["Resultados chegam para quem aparece, mesmo nos dias ruins.", "Anônimo"],
  ["Cada grama de proteína conta. Cada copo d'água importa.", "Anônimo"],
  ["Sua única competição é o espelho.", "Anônimo"],
  ["O treino de hoje é o resultado de amanhã.", "Anônimo"],
  ["Cuide do seu corpo. É o único lugar que você tem para viver.", "Jim Rohn"],
  ["Transformar o corpo exige meses. Transformar a mente é para a vida toda.", "Anônimo"],
  ["Comer bem não é dieta. É respeito por si mesmo.", "Anônimo"],
  ["Faça com que cada treino conte.", "Anônimo"],
  ["Você não precisa ser ótimo para começar, mas precisa começar para ser ótimo.", "Zig Ziglar"],
  ["Não é sobre ser o melhor do mundo. É sobre ser melhor do que você era ontem.", "Anônimo"],
  ["Sonhe grande, trabalhe duro, mantenha o foco.", "Anônimo"],
  ["Gênio é 1% inspiração e 99% transpiração.", "Thomas Edison"],
  ["Primeiro, você define sua rotina. Depois, sua rotina define você.", "Anônimo"],
  // ── Estoicismo ──────────────────────────────────────────────────────
  ["Suporta e abstém-te.", "Epicteto"],
  ["Nunca digas que perdi algo — diz que devolvi o que não era teu.", "Epicteto"],
  ["Não peça que as coisas aconteçam como você quer. Queira que aconteçam como são, e será feliz.", "Epicteto"],
  ["Primeiro, diga a si mesmo quem você quer ser. Depois, faça o que precisa fazer.", "Epicteto"],
  ["É impossível para um homem aprender o que ele acha que já sabe.", "Epicteto"],
  ["O homem que sofre antes de necessário, sofre mais do que necessário.", "Sêneca"],
  ["A vida não é curta — nós é que a tornamos curta desperdiçando-a.", "Sêneca"],
  ["Rebus angustis animosus atque fortis appare. Seja corajoso e forte nos momentos difíceis.", "Sêneca"],
  ["Nusquam est qui ubique est. Quem está em todo lugar, não está em lugar nenhum.", "Sêneca"],
  ["Dum differtur vita transcurrit. Enquanto adiamos, a vida passa.", "Sêneca"],
  ["Você tem poder sobre sua mente, não sobre eventos externos. Perceba isso e encontrará força.", "Marco Aurélio"],
  ["A qualidade da sua vida é determinada pela qualidade dos seus pensamentos.", "Marco Aurélio"],
  ["Perde tempo quem estuda outra coisa que não seja o aperfeiçoamento de si mesmo.", "Marco Aurélio"],
  ["Nada tem tanto poder de ampliar a mente quanto a capacidade de investigar metodicamente tudo.", "Marco Aurélio"],
  ["O obstáculo é o caminho.", "Marco Aurélio"],
  ["Dificultam o que é simples quem não consegue fazer o que é difícil.", "Marco Aurélio"],
  ["Concentre-se no que está em seu poder. Ignore o restante.", "Marco Aurélio"],
  ["Viva de acordo com a natureza — isso é sabedoria.", "Zenão de Cítio"],
  ["A filosofia não promete nada externo ao homem, mas treina a sua alma.", "Musônio Rufo"],
  ["O corajoso não é o que não sente medo, mas o que conquista o medo.", "Crisipo"],
  // ── Filósofos Gregos ────────────────────────────────────────────────
  ["Conhece-te a ti mesmo.", "Sócrates"],
  ["A vida não examinada não vale ser vivida.", "Sócrates"],
  ["A riqueza não traz virtude, mas a virtude traz riqueza e tudo o mais.", "Sócrates"],
  ["Uma coisa que eu sei, é que nada sei.", "Sócrates"],
  ["A maior vitória é a vitória sobre si mesmo.", "Platão"],
  ["O começo é a parte mais importante de qualquer trabalho.", "Platão"],
  ["Somos o que repetidamente fazemos. A excelência não é um ato, mas um hábito.", "Aristóteles"],
  ["A felicidade depende de nós mesmos.", "Aristóteles"],
  ["Educai as crianças, assim não será preciso punir os homens.", "Pitágoras"],
  ["Não busques que as coisas que acontecem sejam como você quer, mas queira que sejam como são.", "Heráclito"],
  ["Tudo flui. Nada é permanente.", "Heráclito"],
  ["A medida é o melhor.", "Cleóbulo de Lindos"],
  ["O homem é a medida de todas as coisas.", "Protágoras"],
  // ── Alexandre o Grande ──────────────────────────────────────────────
  ["Não existe nada impossível para aquele que tenta.", "Alexandre o Grande"],
  ["Não me importo com as batalhas que terei de travar. Importa-me as batalhas que meu inimigo pensa que vai travar.", "Alexandre o Grande"],
  ["A glória não está em nunca cair, mas em erguer-se cada vez que se cai.", "Alexandre o Grande"],
  ["Eu moriria de vergonha se fosse superado por um adversário.", "Alexandre o Grande"],
  ["Não existe um grande talento sem uma grande vontade de ferro.", "Alexandre o Grande"],
  // ── Sun Tzu ─────────────────────────────────────────────────────────
  ["Se você conhece o inimigo e a si mesmo, não precisa temer o resultado de cem batalhas.", "Sun Tzu"],
  ["A vitória suprema é derrotar o inimigo sem lutar.", "Sun Tzu"],
  ["Que seus planos sejam sombrios e impenetráveis como a noite, e quando você se mover, caia como um raio.", "Sun Tzu"],
  ["Oportunidades se multiplicam à medida que são aproveitadas.", "Sun Tzu"],
  ["Aquele que sabe quando lutar e quando não lutar, vencerá.", "Sun Tzu"],
  ["No meio do caos, existe também oportunidade.", "Sun Tzu"],
  ["Toda batalha é vencida antes de ser travada.", "Sun Tzu"],
  ["Seja rápido como o trovão que irrompe antes que você possa cobrir seus ouvidos.", "Sun Tzu"],
  // ── Maquiavel ───────────────────────────────────────────────────────
  ["É melhor ser temido do que amado, se você não pode ser ambos.", "Maquiavel"],
  ["Nunca perca uma boa crise. Nela residem as maiores oportunidades.", "Maquiavel"],
  ["O fim justifica os meios — mas somente o sábio sabe escolher os meios certos.", "Maquiavel"],
  ["Aquele que constrói sobre o povo constrói sobre o barro. Aquele que constrói sobre si mesmo, constrói sobre rocha.", "Maquiavel"],
  ["Não existe remédio para o tempo perdido.", "Maquiavel"],
  ["Os homens são tão simples e obedecem tão prontamente às necessidades imediatas que aquele que engana sempre encontrará os que se deixam enganar.", "Maquiavel"],
  // ── Outras figuras históricas ────────────────────────────────────
  ["Ou encontro um caminho, ou abro um.", "Aníbal Barca"],
  ["O segredo do sucesso é a constância do propósito.", "Benjamin Disraeli"],
  ["O sucesso não é final, o fracasso não é fatal. O que conta é a coragem de continuar.", "Winston Churchill"],
  ["Nunca, nunca, nunca desista.", "Winston Churchill"],
  ["Eu não falhei. Só descobri 10.000 maneiras que não funcionam.", "Thomas Edison"],
  ["A jornada de mil milhas começa com um único passo.", "Lao Tsé"],
  ["A água que corre amolece a pedra.", "Bruce Lee"],
  ["Seja como a água: ela não tem forma, mas toma a forma de tudo.", "Bruce Lee"],
  ["O conhecimento fala, mas a sabedoria escuta.", "Jimi Hendrix"],
  ["O único modo de fazer um excelente trabalho é amar o que faz.", "Steve Jobs"],
  ["Se você sempre faz o que sempre fez, sempre vai obter o que sempre obteve.", "Tony Robbins"],
  ["Não limite seus desafios. Desafie seus limites.", "Jerry Dunn"],
  ["Vá devagar, mas nunca de ré.", "Confúcio"],
  ["Não importa o quão devagar você vai, desde que não pare.", "Confúcio"],
  ["Antes de ser um líder, o sucesso é sobre crescimento pessoal. Depois, é sobre cultivar o crescimento nos outros.", "Jack Welch"],
];